server:
  port: 80


jwt:
  secretKey: "55d5430e17864da9db4h8dbd64a63777be5c1a7f06k92197c9b8113a3b552l60"
  expireDate: 10

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contract_creator
    username: postgres
    password: Sobirov0717
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
