spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contract_creator
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
server:
  port: 8081